
name: Python application

on: [ push , workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 hacking pytest pytest-cov tqdm
      - name: Lint with flake8
        run: |
          flake8 . --config .flake8
      - name: Test with pytest
        run: |
          pytest -vv test_main.py --capture=no . --cov --cov-report=xml
      - uses: codecov/codecov-action@v1